### ISSUE TITLE
wrong '.MYSQL_PREFIX.'

### ISSUE THREAD

**Issue by Caaine** [pabp/bhoptimer-webstats#1]
when i use define('MYSQL_PREFIX', 'COURSE_');

Wrong >$result = mysqli_query($connection, 'SELECT DISTINCT '.MYSQL_PREFIX.'map FROM mapzones ORDER BY map ASC;');
SELECT DISTINCT COURSE_map FROM mapzones ORDER BY map ASC

Right > $result = mysqli_query($connection, 'SELECT DISTINCT map FROM '.MYSQL_PREFIX.'mapzones ORDER BY map ASC;');
SELECT DISTINCT map FROM COURSE_mapzones ORDER BY map ASC

**Comment by pabp** [comment]
Merged it, thanks for the fix.
